- name: Create jenkins telegraf configuration file
  copy:
    src: jenkins.conf
    dest: /etc/telegraf/telegraf.d/jenkins.conf
    mode: 0755
    group: telegraf
    owner: s_ansible
  notify: 'reload telegraf'
  become: true
