- name: Create burrow telegraf configuration file
  template:
    src: burrow.conf.j2
    dest: /etc/telegraf/telegraf.d/burrow.conf
    mode: 0755
    group: telegraf
    owner: s_ansible
  notify: 'reload telegraf'
  become: true
