- name: Create telegraf internal configuration file
  template:
    src: telegraf_internal.j2
    dest: /etc/telegraf/telegraf.d/telegraf_internal.conf
    mode: 0755
    group: telegraf
    owner: s_ansible
  notify: 'reload telegraf'
  become: true
