---
- name: Get pools that are in wide_ip
  local_action: >
    bigip_gtm_facts
    server={{ f5_server }}
    user={{ f5_username }}
    password={{ f5_password }}
    include=wide_ip
    wide_ip={{ f5_wide_ip }}
  register: pools
  tags:
    - enable
    - disable

- name: Assert pool, wide_ip is defined and pool belongs to wide_ip
  assert:
    that:
      - "f5_pool in pools|string"
  tags:
    - enable
    - disable

- name: Disable pool
  local_action: >
    bigip_gtm_pool
    server={{ f5_server }}
    user={{ f5_username }}
    password={{ f5_password }}
    state=disabled
    pool={{ f5_pool }}
    partition=Common
  tags: disable

- name: Get virtual server in pool
  local_action: >
    bigip_gtm_facts
    server={{ f5_server }}
    user={{ f5_username }}
    password={{ f5_password }}
    include=virtual_server
    pool={{ f5_pool }}
    partition=Common
  register: virtual_server
  tags: enable

- name: Get virtual server status
  local_action: >
    bigip_gtm_facts
    server={{ f5_server }}
    user={{ f5_username }}
    password={{ f5_password }}
    include=virtual_server
    virtual_server_name={{ virtual_server.virtual_server.name }}
    virtual_server_server={{ virtual_server.virtual_server.server }}
    partition=Common
  register: virtual_server_status
  tags: enable

- name: Assert that virtual server is available
  assert:
    that:
      - "'AVAILABILITY_STATUS_GREEN' in virtual_server_status.status|string"
  tags: enable

- name: Enable virtual server when its disabled
  local_action: >
    bigip_gtm_virtual_server
    server={{ f5_server }}
    user={{ f5_username }}
    password={{ f5_password }}
    virtual_server_name={{ virtual_server.virtual_server.name }}
    virtual_server_server={{ virtual_server.virtual_server.server }}
    state=enabled
  tags: enable
  when: "'ENABLED_STATUS_DISABLED' in virtual_server_status.status|string"

- name: Get virtual server status in case it was just enabled
  local_action: >
    bigip_gtm_facts
    server={{ f5_server }}
    user={{ f5_username }}
    password={{ f5_password }}
    include=virtual_server
    virtual_server_name={{ virtual_server.virtual_server.name }}
    virtual_server_server={{ virtual_server.virtual_server.server }}
    partition=Common
  register: virtual_server_status
  tags: enable

- name: Assert that virtual server is available
  assert:
    that:
      - "'AVAILABILITY_STATUS_GREEN' in virtual_server_status.status|string"
  tags: enable

- name: Assert that virtual server is enabled
  assert:
    that:
      - "'ENABLED_STATUS_ENABLED' in virtual_server_status.status|string"
  tags: enable

- name: Enable pool
  local_action: >
    bigip_gtm_pool
    server={{ f5_server }}
    user={{ f5_username }}
    password={{ f5_password }}
    state=enabled
    pool={{ f5_pool }}
    partition=Common
  tags: enable